import localFont from "next/font/local";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import MainLayout from "./components/layouts/MainLayout";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#093545]`}
      >
        <MantineProvider>
          <MainLayout>{children}</MainLayout>
        </MantineProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
